on: 
  push:
    branches:
      main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: business54.web-hosting.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        server-dir: /
        port: 21
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/uploads**
          **/live/includes/conndb.php**
          **/vfm-admin/_content/users/users.php**
          **/vfm-admin/config.php**
